---
collections:
  - name: community.general
    version: 5.0.2
    source: https://hub01.localdomain/api/galaxy/content/community/

  # - name: https://github.com/shellclear/aap.git
  #   version: main
  #   type: git 

  - name: ppacific.aap
    version: 5.0.2
    source: https://hub01.localdomain/api/galaxy/content/published/
